### ISSUE TITLE
Sirupsen got renamed to sirupsen

### ISSUE THREAD

**Issue by vincentvanderweele** [tarent/lib-compose#47] opened 2017-05-22 09:24 UTC
After [some hassle](https://github.com/sirupsen/logrus/issues/451), Sirupsen/logrus got [renamed for good](https://github.com/sirupsen/logrus#case-sensitivity) to sirupsen/logrus.

In this repo, the [capitalised name is still used](https://github.com/tarent/lib-compose/blob/master/logging/logger.go#L6). This gives me the following error when I try to `go get github.com/tarent/loginsrv`:

> case-insensitive import collision: "github.com/Sirupsen/logrus" and "github.com/sirupsen/logrus"

I'm a bit hesitant to just create a PR renaming the import, exactly because of the linked issue thread. I'm not sure if that will cause breaks for users of this repo. What do you think?

**Comment by stweiz** [comment] 2017-05-22 09:29
As you see here, the issue is a bit bigger: https://github.com/sirupsen/logrus/issues/543
Also sirupsen has import paths of their own projects, where the first letter is either a capital or not.
I think, first it must be fixed in their projects.
A workaround would be, to make forks of logrus and lib-compose and set all Sirupsen imports to lower-case.

Do we have another option in this project, to avoid this issue @smancke ?

**Comment by smancke** [comment] 2017-05-22 09:32
As @domano mentioned: We will only wait a couple of hours to see, if sirupsen get's this solved. If not, we create a fork and change the imports of all our project the fork, until the issues is solved.

**Comment by domano** [comment] 2017-05-22 10:12
Yeah, i will create the fork after lunch :)

**Comment by vincentvanderweele** [comment] 2017-05-22 10:28
Thanks for the quick responses and good to see you were already on it days ago 👍

**Comment by smancke** [comment] 2017-05-22 20:25
I've created a PR for pointing to the new location.
Also I copied over the logging package to loginsrv, and pushed that into master.
There is no good reason for loginsrv to rely on a cascade of packages to put out a few log statements.

So @vincentvanderweele you should be able to continue using loginsrv, now.

**Closed** 2017-05-23 08:03 UTC
